version: "3.7"

networks:
  proxy:
    external: true
  backend:

services:
  nginx:
   image: nginx:stable-alpine
   container_name: nginx
   restart: unless-stopped
   networks:
     - proxy
     - backend
   ports:
     - 80:80
     - 443:443
   volumes:
     - ../laravel:/var/www/laravel
     - ../vue:/var/www/vue
     - ../nginx/conf:/etc/nginx/conf.d
     - ../nginx/log:/var/log/nginx
     - ../nginx/certs:/etc/ssl/certs
   working_dir: /var/log/nginx
   depends_on:
     - laravel
     - vue
  vue:
    image: node:16
    container_name: vue
    restart: unless-stopped
    networks:
      - proxy
      - backend
    volumes:
      - ../vue:/var/www/vue
    working_dir: /var/www/vue
    command: "tail -f /dev/null"

  laravel:
    build:
      context: .
      dockerfile: laravel.Dockerfile
    container_name: laravel
    restart: unless-stopped
    networks:
      - proxy
      - backend
    ports:
      - 9000:9000
    volumes:
      - ../laravel:/var/www/laravel
    working_dir: /var/www/laravel

